service: ss3fs
custom:
  sourceBucketArn: arn:aws:s3:::${file(./config.${self:provider.stage}.yml):SOURCE_BUCKET}
  destinationBucketArn: arn:aws:s3:::${file(./config.${self:provider.stage}.yml):DESTINATION_BUCKET}

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  environment: ${file(./config.${self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:GetObject'
        - 's3:GetObjectAcl'
      Resource:
        - ${self:custom.sourceBucketArn}
        - Fn::If:
            - HasNotSourceFolder
            - Fn::Join:
                - '/'
                - - ${self:custom.sourceBucketArn}
                  - '*'
            - Fn::Join:
                - '/'
                - - ${self:custom.sourceBucketArn}
                  - ${self:provider.environment.SOURCE_FOLDER}
                  - '*'
    - Effect: Allow
      Action:
        - 's3:PutObject'
        - 's3:PutObjectAcl'
        - 's3:DeleteObject'
      Resource:
        - ${self:custom.destinationBucketArn}
        - Fn::If:
            - HasNotDestinationFolder
            - Fn::Join:
                - '/'
                - - ${self:custom.destinationBucketArn}
                  - '*'
            - Fn::Join:
                - '/'
                - - ${self:custom.destinationBucketArn}
                  - ${self:provider.environment.DESTINATION_FOLDER}
                  - '*'

functions:
  sync:
    handler: handler.sync
    events:
      - s3:
          bucket: ${self:provider.environment.SOURCE_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:provider.environment.SOURCE_FOLDER}/
          existing: true
      - s3:
          bucket: ${self:provider.environment.SOURCE_BUCKET}
          event: s3:ObjectRemoved:*
          rules:
            - prefix: ${self:provider.environment.SOURCE_FOLDER}/
          existing: true

resources:
  Conditions:
    HasNotSourceFolder:
      Fn::Equals:
        - ${self:provider.environment.SOURCE_FOLDER}
        - ''
    HasNotDestinationFolder:
      Fn::Equals:
        - ${self:provider.environment.DESTINATION_FOLDER}
        - ''
package:
  exclude:
    - serverless/**
    - extra/**